server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/yesu24
    #url: jdbc:mariadb://localhost:3306/shop?serverTimezone=Asia/Seoul
    username: sa
    #driver-class-name: org.mariadb.jdbc.Driver
    password:

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql : true # sql 예쁘게 출력
        default_batch_fetch_size: 100 # 일대다 컬렉션 조회 최적화,

    show-sql: true  # sql 출력
    open-in-view: false

logging:
  level:
    org.hibernate.type: trace
