server:
  ssl:
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: root

  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/shop?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: org.mariadb.jdbc.Driver
    username: dbuser
    #username: ${DB_USERNAME}
    password: 12341234

    #driver-class-name: org.h2.Driver
    #url: jdbc:h2:tcp://localhost/~/yesu24
    #username: sa
    #password:




  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql : true # sql 예쁘게 출력
        default_batch_fetch_size: 100 # 일대다 컬렉션 조회 최적화,
    show-sql: true  # sql 출력
    open-in-view: false

logging:
  level:
    org.hibernate.type: trace
